Feat/user withdraw
ospiem/gophermart pull request #3
Opened 2024-02-04 08:27 UTC by ospiem

2024-02-05 14:11 UTC, s-shpak requested changes
Сделай так, чтобы линтер и автотесты проходили и посмотри первые замечания, пожалуйста

2024-02-05 14:11 UTC, s-shpak commented on cmd/gophermart/main.go
> +				delay := delayMap[restclient.DelayTime]
вместо map и мьютекса можно использовать примитивы пердоставляемые `atomic`

2024-02-05 14:11 UTC, s-shpak commented on internal/restclient/restclient.go
> +	_ = delayMap[DelayTime]
Что именно делает эта строка ?

2024-02-05 14:11 UTC, s-shpak commented on internal/restclient/restclient.go
> +	return models.Order{}, errors.New("unknown status code")
Статус-код тоже можно добавить в сообщение ошибки

2024-02-05 14:11 UTC, s-shpak commented on internal/storage/postgres/migrations/00001_init.up.sql
> +    withdraw UUID,
Может ли это поле быть `NULL`? Если да, то поля в любом случае надо помечать как `NULL/NOT NULL`

2024-02-05 14:11 UTC, s-shpak commented on internal/storage/postgres/migrations/00001_init.up.sql
> +ALTER TABLE orders ADD FOREIGN KEY (withdraw) REFERENCES withdraws(id);
Этот запрос также должен быть внутри коммита

2024-02-05 14:11 UTC, s-shpak commented on internal/transport/http/v1/handlers.go
> +	//re := regexp.MustCompile(`^\d+$`)
deadcode ?

2024-02-05 14:11 UTC, s-shpak commented on internal/transport/http/v1/middleware/compress/compress.go
> +		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
Зачем оборачивать middleware два раза ?

2024-02-05 14:14 UTC, ospiem commented on internal/restclient/restclient.go
> +	_ = delayMap[DelayTime]
я пытаюсь прочитать из мапы, функция будет выполняться дальше, если мапа не заблокирована. Блокирую ее в другой горутине на время, полученное от сервиса accrual с 429 статусом

2024-02-06 15:57 UTC, ospiem commented on internal/restclient/restclient.go
> +	_ = delayMap[DelayTime]
пытается прочитать значение из map. Если получил 429 от accural, то map блокируется

2024-02-06 17:33 UTC, ospiem commented on internal/transport/http/v1/middleware/compress/compress.go
> +		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
чтобы передать логгер в middleware

2024-02-13 08:49 UTC, s-shpak approved these changes

2024-02-13 09:06 UTC, merged